version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bitbudget-local
    ports:
      - "5432:5432"